destination: _site/
url: "http://127.0.0.1:4013"
baseurl: "/murat-pdf"
port: 4011
output: pdf
product: portfolio
print_title: Curriculum Vitae  
print_subtitle: Murat Kahveci, Ph.D.
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: murat_sidebar
